-- Piloto B2B (Tier 1) aprovado em 2026-08-07: ES completo (78 municípios) +
-- 1 metrópole de maior volume por região, com Sudeste representado por
-- Vitória (já no ES) + Belo Horizonte em vez de São Paulo — pedido
-- explícito do cliente (São Paulo já tem muita concorrência no nicho).
--
-- Remove os 2 registros de demonstração (São Paulo, Rio de Janeiro) criados
-- na migration 0022 só para testar a malha de links antes de existir um
-- lote real — mantê-los ativos entraria em conflito direto com a decisão
-- acima assim que `generateStaticParams`/sitemap passarem a ler todas as
-- cidades ativas para os tipos B2B.
delete from public.geo_cities where uf in ('sp', 'rj') and slug in ('sao-paulo', 'rio-de-janeiro');

insert into public.geo_cities (slug, uf, name, uf_name, region, tier) values
  ('serra', 'es', 'Serra', 'Espírito Santo', 'sudeste', 1),
  ('vila-velha', 'es', 'Vila Velha', 'Espírito Santo', 'sudeste', 1),
  ('cariacica', 'es', 'Cariacica', 'Espírito Santo', 'sudeste', 1),
  ('vitoria', 'es', 'Vitória', 'Espírito Santo', 'sudeste', 1),
  ('cachoeiro-de-itapemirim', 'es', 'Cachoeiro de Itapemirim', 'Espírito Santo', 'sudeste', 1),
  ('linhares', 'es', 'Linhares', 'Espírito Santo', 'sudeste', 1),
  ('guarapari', 'es', 'Guarapari', 'Espírito Santo', 'sudeste', 1),
  ('sao-mateus', 'es', 'São Mateus', 'Espírito Santo', 'sudeste', 1),
  ('colatina', 'es', 'Colatina', 'Espírito Santo', 'sudeste', 1),
  ('aracruz', 'es', 'Aracruz', 'Espírito Santo', 'sudeste', 2),
  ('viana', 'es', 'Viana', 'Espírito Santo', 'sudeste', 2),
  ('nova-venecia', 'es', 'Nova Venécia', 'Espírito Santo', 'sudeste', 2),
  ('marataizes', 'es', 'Marataízes', 'Espírito Santo', 'sudeste', 2),
  ('santa-maria-de-jetiba', 'es', 'Santa Maria de Jetibá', 'Espírito Santo', 'sudeste', 2),
  ('barra-de-sao-francisco', 'es', 'Barra de São Francisco', 'Espírito Santo', 'sudeste', 2),
  ('itapemirim', 'es', 'Itapemirim', 'Espírito Santo', 'sudeste', 2),
  ('castelo', 'es', 'Castelo', 'Espírito Santo', 'sudeste', 2),
  ('domingos-martins', 'es', 'Domingos Martins', 'Espírito Santo', 'sudeste', 2),
  ('sao-gabriel-da-palha', 'es', 'São Gabriel da Palha', 'Espírito Santo', 'sudeste', 2),
  ('anchieta', 'es', 'Anchieta', 'Espírito Santo', 'sudeste', 2),
  ('baixo-guandu', 'es', 'Baixo Guandu', 'Espírito Santo', 'sudeste', 2),
  ('afonso-claudio', 'es', 'Afonso Cláudio', 'Espírito Santo', 'sudeste', 2),
  ('jaguare', 'es', 'Jaguaré', 'Espírito Santo', 'sudeste', 2),
  ('guacui', 'es', 'Guaçuí', 'Espírito Santo', 'sudeste', 2),
  ('alegre', 'es', 'Alegre', 'Espírito Santo', 'sudeste', 2),
  ('iuna', 'es', 'Iúna', 'Espírito Santo', 'sudeste', 2),
  ('conceicao-da-barra', 'es', 'Conceição da Barra', 'Espírito Santo', 'sudeste', 2),
  ('sooretama', 'es', 'Sooretama', 'Espírito Santo', 'sudeste', 2),
  ('ibatiba', 'es', 'Ibatiba', 'Espírito Santo', 'sudeste', 2),
  ('venda-nova-do-imigrante', 'es', 'Venda Nova do Imigrante', 'Espírito Santo', 'sudeste', 2),
  ('mimoso-do-sul', 'es', 'Mimoso do Sul', 'Espírito Santo', 'sudeste', 2),
  ('pinheiros', 'es', 'Pinheiros', 'Espírito Santo', 'sudeste', 2),
  ('piuma', 'es', 'Piúma', 'Espírito Santo', 'sudeste', 2),
  ('santa-teresa', 'es', 'Santa Teresa', 'Espírito Santo', 'sudeste', 2),
  ('ecoporanga', 'es', 'Ecoporanga', 'Espírito Santo', 'sudeste', 2),
  ('pedro-canario', 'es', 'Pedro Canário', 'Espírito Santo', 'sudeste', 2),
  ('vargem-alta', 'es', 'Vargem Alta', 'Espírito Santo', 'sudeste', 3),
  ('rio-bananal', 'es', 'Rio Bananal', 'Espírito Santo', 'sudeste', 3),
  ('montanha', 'es', 'Montanha', 'Espírito Santo', 'sudeste', 3),
  ('pancas', 'es', 'Pancas', 'Espírito Santo', 'sudeste', 3),
  ('marechal-floriano', 'es', 'Marechal Floriano', 'Espírito Santo', 'sudeste', 3),
  ('fundao', 'es', 'Fundão', 'Espírito Santo', 'sudeste', 3),
  ('muniz-freire', 'es', 'Muniz Freire', 'Espírito Santo', 'sudeste', 3),
  ('presidente-kennedy', 'es', 'Presidente Kennedy', 'Espírito Santo', 'sudeste', 3),
  ('irupi', 'es', 'Irupi', 'Espírito Santo', 'sudeste', 3),
  ('alfredo-chaves', 'es', 'Alfredo Chaves', 'Espírito Santo', 'sudeste', 3),
  ('joao-neiva', 'es', 'João Neiva', 'Espírito Santo', 'sudeste', 3),
  ('vila-valerio', 'es', 'Vila Valério', 'Espírito Santo', 'sudeste', 3),
  ('muqui', 'es', 'Muqui', 'Espírito Santo', 'sudeste', 3),
  ('boa-esperanca', 'es', 'Boa Esperança', 'Espírito Santo', 'sudeste', 3),
  ('itaguacu', 'es', 'Itaguaçu', 'Espírito Santo', 'sudeste', 3),
  ('santa-leopoldina', 'es', 'Santa Leopoldina', 'Espírito Santo', 'sudeste', 3),
  ('brejetuba', 'es', 'Brejetuba', 'Espírito Santo', 'sudeste', 3),
  ('mantenopolis', 'es', 'Mantenópolis', 'Espírito Santo', 'sudeste', 3),
  ('marilandia', 'es', 'Marilândia', 'Espírito Santo', 'sudeste', 3),
  ('iconha', 'es', 'Iconha', 'Espírito Santo', 'sudeste', 3),
  ('agua-doce-do-norte', 'es', 'Água Doce do Norte', 'Espírito Santo', 'sudeste', 3),
  ('conceicao-do-castelo', 'es', 'Conceição do Castelo', 'Espírito Santo', 'sudeste', 3),
  ('ibiracu', 'es', 'Ibiraçu', 'Espírito Santo', 'sudeste', 3),
  ('jeronimo-monteiro', 'es', 'Jerônimo Monteiro', 'Espírito Santo', 'sudeste', 3),
  ('laranja-da-terra', 'es', 'Laranja da Terra', 'Espírito Santo', 'sudeste', 3),
  ('rio-novo-do-sul', 'es', 'Rio Novo do Sul', 'Espírito Santo', 'sudeste', 3),
  ('governador-lindenberg', 'es', 'Governador Lindenberg', 'Espírito Santo', 'sudeste', 3),
  ('sao-jose-do-calcado', 'es', 'São José do Calçado', 'Espírito Santo', 'sudeste', 3),
  ('sao-roque-do-canaa', 'es', 'São Roque do Canaã', 'Espírito Santo', 'sudeste', 3),
  ('atilio-vivacqua', 'es', 'Atílio Vivácqua', 'Espírito Santo', 'sudeste', 3),
  ('itarana', 'es', 'Itarana', 'Espírito Santo', 'sudeste', 3),
  ('bom-jesus-do-norte', 'es', 'Bom Jesus do Norte', 'Espírito Santo', 'sudeste', 3),
  ('aguia-branca', 'es', 'Águia Branca', 'Espírito Santo', 'sudeste', 3),
  ('ibitirama', 'es', 'Ibitirama', 'Espírito Santo', 'sudeste', 3),
  ('vila-pavao', 'es', 'Vila Pavão', 'Espírito Santo', 'sudeste', 3),
  ('sao-domingos-do-norte', 'es', 'São Domingos do Norte', 'Espírito Santo', 'sudeste', 3),
  ('alto-rio-novo', 'es', 'Alto Rio Novo', 'Espírito Santo', 'sudeste', 3),
  ('apiaca', 'es', 'Apiacá', 'Espírito Santo', 'sudeste', 3),
  ('dores-do-rio-preto', 'es', 'Dores do Rio Preto', 'Espírito Santo', 'sudeste', 3),
  ('ponto-belo', 'es', 'Ponto Belo', 'Espírito Santo', 'sudeste', 3),
  ('mucurici', 'es', 'Mucurici', 'Espírito Santo', 'sudeste', 3),
  ('divino-de-sao-lourenco', 'es', 'Divino de São Lourenço', 'Espírito Santo', 'sudeste', 3),
  ('belo-horizonte', 'mg', 'Belo Horizonte', 'Minas Gerais', 'sudeste', 1),
  ('salvador', 'ba', 'Salvador', 'Bahia', 'nordeste', 1),
  ('brasilia', 'df', 'Brasília', 'Distrito Federal', 'centro-oeste', 1),
  ('curitiba', 'pr', 'Curitiba', 'Paraná', 'sul', 1),
  ('manaus', 'am', 'Manaus', 'Amazonas', 'norte', 1)
on conflict (uf, slug) do nothing;
